apiVersion: v1
kind: Secret
metadata:
  name: b-secret-{{ version | regex_replace('[^A-Za-z0-9-]', '-') }}
  namespace: {{ env }}
  labels:
    prefix: b-secret
type: Opaque
data:
  b_secret: "{{ 'not_very_secret_b_v2' | b64encode }}"
