- name: ensure namespace exists
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ kuberesource_namespace }}"
    state: present

- name: empty manifest and secret lists (important if role is run twice!)
  set_fact:
    kuberesource_manifests: []

- debug:
    msg: "{{ item | k8s_config_resource_name }}"
  loop: "{{ kuberesource_configmaps.values() }}"

- debug:
    msg: "{{ item | k8s_config_resource_name }}"
  loop: "{{ kuberesource_secrets.values() }}"

- name: create manifests list
  set_fact:
    kuberesource_manifests: >
      {{ kuberesource_manifests + lookup('template', item)|from_yaml_all|list }}
  loop: "{{ kuberesource_manifest_files }}"

- name: create configmaps
  k8s:
    definition: "{{ item }}"
    append_hash: yes
  loop: "{{ kuberesource_configmaps.values() }}"

- name: create secrets
  k8s:
    definition: "{{ item }}"
    append_hash: yes
  loop: "{{ kuberesource_secrets.values() }}"
  no_log: yes

- name: apply all resource definitions in order
  k8s:
    definition: "{{ item }}"
  loop: "{{ kuberesource_manifests }}"
