apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ application }}
  namespace: {{ kube_resource_namespace }}
  labels:
    {{ kube_deployment_labels | to_nice_yaml(indent=2) | indent(4) }}
spec:
  replicas: {{ kube_deployment_replicas }}
  selector:
    matchLabels:
      {{ kube_resource_labels | to_nice_yaml(indent=2) | indent(6) }}
  template:
    metadata:
      labels:
        {{ kube_resource_labels | to_nice_yaml(indent=2) | indent(8) }}
    spec:
      containers:
        - name: {{ application }}
          # Normally container tag would come from inventory but we want to show changes over time
          image: {{ (container_registry|default())|ternary(container_registry + "/", "") }}{{ container_image }}:blue
          imagePullPolicy: {{ image_pull_policy }}
          ports:
            - containerPort: 5000
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: AN_ENV_VAR
              valueFrom:
                secretKeyRef:
                  name: a-secret
                  key: AN_ENV_VAR
          envFrom:
            - configMapRef:
                name: a-configmap
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ application }}
  namespace: {{ kube_resource_namespace }}
  labels:
    {{ kube_resource_labels | to_nice_yaml(indent=2) | indent(4) }}
spec:
  ports:
  - port: 8080 # the port that this service should serve on
    # the container on each pod to connect to, can be a name
    # (e.g. 'www') or a number (e.g. 80)
    targetPort: 5000
    protocol: TCP
  # just like the selector in the deployment,
  # but this time it identifies the set of pods to load balance
  # traffic to.
  selector:
    {{ kube_resource_labels | to_nice_yaml(indent=2) | indent(4) }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ application }}
  namespace: {{ kube_resource_namespace }}
spec:
  rules:
  - host: {{ kube_resource_fqdn }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ application }}
          servicePort: 8080
